name: 'CI/CD'

on:
  push:
    branches: ["develop", "main"]

env:
  GAR_LOCATION: "europe-west1-docker.pkg.dev/${{secrets.PROJECT_ID}}/objectchecker"


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: '${{ secrets.WIF_SA }}'
    - name: Build image
      run: docker build . --file Dockerfile --tag ${{ env.GAR_LOCATION }}
      # working-directory: ../
    - name: Push image
      run: docker push ${{ env.GAR_LOCATION }}